### PR TITLE
chart - update chart to 0.1.10 to include recent changes

### PR DESCRIPTION
**Pull request by goshlanguage**
# update chart to 0.1.10 to include recent changes

Can we please bump the chart so recent merges can be used?

## How to use

chart version can be specified when installing the chart

### CODE REVIEW

**Comment by goshlanguage** [comment]
@yolossn can we please cut a release with the recent changes?

**Comment by yolossn** [comment]
@goshlanguage Sorry, I am on vacation. Didn't see this earlier.

**Comment by yolossn** [comment]
Release successful. Highly appreciate being patient and understanding.

**Comment by goshlanguage** [comment]
Thank you so much for all of your help, I hope you have a great time off!

**Pull request merged**
