### PR TITLE
go.mod: update all the dependencies used

### PR DESCRIPTION
**Pull request by vbatts**
Ran `go get -u ./...`

certainly more to test than updating a package at a time, but topping
off all the things for update's sake.

Signed-off-by: Vincent Batts <vbatts@kinvolk.io>

(will need to be rebased on https://github.com/kinvolk/nebraska/pull/295)

### CODE REVIEW

**Review by joaquimrocha — CHANGES_REQUESTED** [review]
Same comment as in https://github.com/kinvolk/nebraska/pull/295#pullrequestreview-523728867 .

Nitpick: The commit's description usually also starts with a capital.

I am not sure what you mean with `certainly more to test than updating a package at a time`. But I agree this update is long due. I will keep an eye in the next days to see if I spot any breakage.

**Comment by vbatts** [comment]
the `golang.org/x/text` update was narrow and for a security task. But once I was there, it looks like there was more to update, _which_ has more moving parts that can cause breakages. That's all.

Updated. PTAL.

**Comment by joaquimrocha** [comment]
> the `golang.org/x/text` update was narrow and for a security task. But once I was there, it looks like there was more to update, _which_ has more moving parts that can cause breakages. That's all.
> 
> Updated. PTAL.

Thanks.
Since you have to rebase (in order to pass the CI checks), please use the impreative mood (`go.mod: update all the dependencies used` instead of `updated`).

**Comment by vbatts** [comment]
funny, i don't understand or identify with imperative voice at all. :grimacing:

**Comment by vbatts** [comment]
updated. PTAL

**Pull request merged**
