### PR TITLE
*.go: repoint go-omaha to kinvolk fork

### PR DESCRIPTION
**Pull request by vbatts**
depends on https://github.com/kinvolk/go-omaha/pull/5

Signed-off-by: Vincent Batts <vbatts@kinvolk.io>

### CODE REVIEW

**Comment by vbatts** [comment]
once the go-omaha PR merges, then this one will need the go.mod updated as well

**Comment by vbatts** [comment]
ok, ready for review

**Review by joaquimrocha — APPROVED** [review]
Usually we prefix backend PRs with "backend:".

**Comment by vbatts** [comment]
@joaquimrocha noted (for future reference)

**Pull request merged**
